[tool.poetry]
name = "EyeTrackVR"
version = "0.2.0"
description = "Opensource, affordable VR eye tracker for VRChat"
authors = ["RedHawk989"]
license = "MIT"
repository = "https://github.com/CommanderPho/EyeTrackVRR"

[tool.poetry.dependencies]
python = "~3.11.0"
python-osc = "^1.8.0"
requests = "^2.28.1"
opencv-python = "^4.6.0.66"
numpy = "~1.23.5"
pye3d = "^0.3.1.post1"
pysimplegui = "^4.60.4"
pydantic = "^2.4.2"
scikit-image = "*"
pyserial = "^3.5"
winotify = [ 
    { version = "^1.1.0", platform = 'win32' }
]
onnxruntime = "^1.13.1"
colorama = "^0.4.6"
taskipy = "^1.10.4"
pytest = "^8.0.0"
pytest-cov = "^4.1.0"
ipykernel = "^6.29.5"
ipython = "^8.26.0"
pip = "^24.2"
flask = "^3.0.3"
imutils = "^0.5.4"
imageio = {extras = ["ffmpeg"], version = "^2.34.1"}
[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
pyinstaller = "^5.6.2"
flake8 = "^5.0.4"


[tool.taskipy.tasks]
dev = "python eyetrackapp.py"

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "-ra -q --cov=. --cov-report html --cov-report term"
pythonpath = "."
python_files = [
    "test_*.py"
]


[tool.poetry.scripts]
install = "poetry: command"   # poetry install is a built-in command, so this script is not needed
run = "python EyeTrackApp/eyetrackapp.py"
pyinstaller = "pyinstaller EyeTrackApp/eyetrackapp.spec EyeTrackApp/eyetrackapp.py"
clean = "python scripts/clean.py" # Python script to handle deletion of files/directories
